#!/usr/bin/env bash
# PF_login v0.10.84 prooflauncher for Raspberry/Linux visual physical proof bundle runs.
# Generated by GENERATE PROOFRUNNER / GENERATE PROOFLAUNCHER workflow.
# It unpacks the repo ZIP, runs required V2 proof commands only, writes real-time logs,
# captures artifacts/operator visual evidence, zips the run folder, and opens the folder containing the ZIP.

set -u -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ZIP_NAME="PF_login_v0.10.85_production_cron_split_full_git.zip"
REPO_ZIP="$SCRIPT_DIR/$REPO_ZIP_NAME"
RUN_TS="$(date +%Y%m%d_%H%M%S)"
RUN_PARENT="$SCRIPT_DIR/prooflauncher_runs"
RUN_DIR="$RUN_PARENT/$RUN_TS"
LOGS_ONLY_STAGE="$RUN_PARENT/${RUN_TS}_logs_only_stage"
WORKSPACE="$RUN_DIR/workspace"
CMD_LOG_DIR="$RUN_DIR/command_logs"
ARTIFACT_DIR="$RUN_DIR/captured_artifacts"
VISUAL_EVIDENCE_DIR="$RUN_DIR/operator_visual_evidence"
MAIN_LOG="$RUN_DIR/prooflauncher.log"
RESULT_ZIP="$RUN_PARENT/${RUN_TS}_prooflauncher_logs.zip"
SUMMARY_FILE="$RUN_DIR/run_summary.txt"

mkdir -p "$CMD_LOG_DIR" "$ARTIFACT_DIR" "$WORKSPACE" "$RUN_PARENT" "$VISUAL_EVIDENCE_DIR"

touch "$MAIN_LOG"
exec > >(tee -a "$MAIN_LOG") 2>&1

log() {
  printf '[%s] %s\n' "$(date --iso-8601=seconds)" "$*"
}

append_summary() {
  printf '%s\n' "$*" >> "$SUMMARY_FILE"
}

write_visual_instructions() {
  cat > "$VISUAL_EVIDENCE_DIR/VISUAL_PHYSICAL_PROOF_INSTRUCTIONS.md" <<'VISUAL'
# V2 Visual Physical Proof Instructions

Backend logs prove cron/runtime/truth events. They do **not** visually prove the physical display.

Add operator evidence to this folder before/while the prooflauncher runs:

1. Photo or video of the real screen showing media.
2. Photo or video where the overlay is visible on top of media.
3. Optional video showing media advances.
4. Optional evidence of screen on/off behavior.

Then copy `operator_confirmation_template.json` to `operator_visual_confirmation.json` and set:

```json
"screenShowsMedia": true,
"overlayVisible": true
```

Accepted media extensions: `.jpg`, `.jpeg`, `.png`, `.webm`, `.mp4`, `.mov`, `.mkv`.
VISUAL

  cat > "$VISUAL_EVIDENCE_DIR/PUT_PHOTOS_OR_VIDEOS_HERE.txt" <<'TXT'
Put physical screen photos/videos in this folder.
The prooflauncher will include this folder in the uploaded log ZIP.
TXT

  if [ ! -f "$VISUAL_EVIDENCE_DIR/operator_visual_confirmation.json" ]; then
    cat > "$VISUAL_EVIDENCE_DIR/operator_confirmation_template.json" <<'JSON'
{
  "operator": "Mihkel",
  "confirmedAt": "REPLACE_WITH_CURRENT_TIME",
  "screenShowsMedia": false,
  "overlayVisible": false,
  "mediaAdvances": false,
  "screenOnOffObserved": false,
  "notes": "Copy this file to operator_visual_confirmation.json and update after adding screen photo/video evidence."
}
JSON
  fi
}

copy_seeded_visual_evidence() {
  local seed_dir="$SCRIPT_DIR/seeded_visual_evidence"
  if [ -d "$seed_dir" ]; then
    log "Copying seeded visual evidence from: $seed_dir"
    cp -a "$seed_dir/." "$VISUAL_EVIDENCE_DIR/" 2>/dev/null || true
  fi
}

open_folder() {
  local folder="$1"
  if command -v xdg-open >/dev/null 2>&1; then
    xdg-open "$folder" >/dev/null 2>&1 || true
  elif command -v gio >/dev/null 2>&1; then
    gio open "$folder" >/dev/null 2>&1 || true
  elif command -v pcmanfm >/dev/null 2>&1; then
    pcmanfm "$folder" >/dev/null 2>&1 || true
  else
    log "No graphical folder opener found. Folder: $folder"
  fi
}

run_shell_cmd() {
  local name="$1"
  shift
  local command_text="$*"
  local log_file="$CMD_LOG_DIR/${name}.log"
  local exit_file="$CMD_LOG_DIR/${name}.exitcode"

  log "START COMMAND: $name"
  log "COMMAND: $command_text"
  printf 'START %s\nCOMMAND %s\n' "$(date --iso-8601=seconds)" "$command_text" > "$log_file"

  set +e
  bash -lc "$command_text" 2>&1 | tee -a "$log_file"
  local code="${PIPESTATUS[0]}"
  set +e

  printf '%s\n' "$code" > "$exit_file"
  log "FINISH COMMAND: $name exit=$code"
  append_summary "$name exit=$code"
  printf '\n'
  return 0
}

create_logs_only_stage() {
  log "Creating logs-only staging folder: $LOGS_ONLY_STAGE"
  rm -rf "$LOGS_ONLY_STAGE"
  mkdir -p "$LOGS_ONLY_STAGE"

  [ -f "$MAIN_LOG" ] && cp -a "$MAIN_LOG" "$LOGS_ONLY_STAGE/prooflauncher.log" || true
  [ -f "$SUMMARY_FILE" ] && cp -a "$SUMMARY_FILE" "$LOGS_ONLY_STAGE/run_summary.txt" || true
  [ -d "$CMD_LOG_DIR" ] && cp -a "$CMD_LOG_DIR" "$LOGS_ONLY_STAGE/command_logs" || true
  [ -d "$ARTIFACT_DIR" ] && cp -a "$ARTIFACT_DIR" "$LOGS_ONLY_STAGE/captured_artifacts" || true
  [ -d "$VISUAL_EVIDENCE_DIR" ] && cp -a "$VISUAL_EVIDENCE_DIR" "$LOGS_ONLY_STAGE/operator_visual_evidence" || true

  # Defense in depth: no extracted repo/workspace/dependencies/git internals are allowed in the upload ZIP.
  find "$LOGS_ONLY_STAGE" \( -name workspace -o -name node_modules -o -name .git \) -type d -prune -exec rm -rf {} + 2>/dev/null || true
  find "$LOGS_ONLY_STAGE" \( -name package.json -o -name package-lock.json \) -type f -delete 2>/dev/null || true

  cat > "$LOGS_ONLY_STAGE/LOG_ZIP_HYGIENE_SELF_CHECK.json" <<HYGIENE
{
  "generatedAt": "$(date --iso-8601=seconds)",
  "rule": "prooflauncher log ZIP must contain logs/artifacts/evidence only, not the extracted repository",
  "excluded": ["workspace/", "node_modules/", ".git/", "package.json", "package-lock.json"],
  "sourceRunDir": "$RUN_DIR",
  "logsOnlyStage": "$LOGS_ONLY_STAGE"
}
HYGIENE
}

zip_run_folder() {
  log "Packaging logs-only prooflauncher ZIP: $RESULT_ZIP"
  mkdir -p "$RUN_PARENT"
  create_logs_only_stage
  rm -f "$RESULT_ZIP" "$RESULT_ZIP.sha256"
  if command -v zip >/dev/null 2>&1; then
    (cd "$RUN_PARENT" && zip -r "$RESULT_ZIP" "$(basename "$LOGS_ONLY_STAGE")" -x '*workspace*' '*node_modules*' '*.git*' '*package.json' '*package-lock.json')
  elif command -v python3 >/dev/null 2>&1; then
    (cd "$RUN_PARENT" && python3 -m zipfile -c "$RESULT_ZIP" "$(basename "$LOGS_ONLY_STAGE")")
  else
    log "WARNING: neither zip nor python3 is available; cannot package logs."
    return 0
  fi
  if command -v sha256sum >/dev/null 2>&1 && [ -f "$RESULT_ZIP" ]; then
    sha256sum "$RESULT_ZIP" | tee "$RESULT_ZIP.sha256"
  fi
}

capture_artifacts() {
  local repo_root="${1:-}"
  log "Capturing artifacts."
  mkdir -p "$ARTIFACT_DIR/npm_logs" "$ARTIFACT_DIR/runtime_artifacts"
  cp -a "$HOME/.npm/_logs/." "$ARTIFACT_DIR/npm_logs/" 2>/dev/null || true
  cp -a "$VISUAL_EVIDENCE_DIR" "$ARTIFACT_DIR/" 2>/dev/null || true

  if [ -n "$repo_root" ] && [ -d "$repo_root" ]; then
    cp -a "$repo_root/runtime_data/proofs" "$ARTIFACT_DIR/runtime_artifacts/" 2>/dev/null || true
    cp -a "$repo_root/runtime_data/v2_worker_truth" "$ARTIFACT_DIR/runtime_artifacts/" 2>/dev/null || true
    cp -a "$repo_root/runtime_data/recovery" "$ARTIFACT_DIR/runtime_artifacts/" 2>/dev/null || true
    cp -a "$repo_root/runtime_data/logs" "$ARTIFACT_DIR/runtime_artifacts/" 2>/dev/null || true
    cp -a "$repo_root/test_runtime_data" "$ARTIFACT_DIR/" 2>/dev/null || true
    (cd "$repo_root" && git status --short > "$CMD_LOG_DIR/git_status_after.log" 2>&1) || true
  fi
}

wait_for_visual_evidence_if_requested() {
  local wait_seconds="${PF_V2_VISUAL_EVIDENCE_WAIT_SECONDS:-0}"
  if ! [[ "$wait_seconds" =~ ^[0-9]+$ ]]; then
    wait_seconds=0
  fi
  if [ "$wait_seconds" -le 0 ]; then
    log "Visual evidence wait disabled. Set PF_V2_VISUAL_EVIDENCE_WAIT_SECONDS=120 to pause before validation."
    return 0
  fi
  log "Waiting $wait_seconds seconds for operator visual evidence in: $VISUAL_EVIDENCE_DIR"
  local elapsed=0
  while [ "$elapsed" -lt "$wait_seconds" ]; do
    sleep 5
    elapsed=$((elapsed + 5))
    log "visual evidence wait elapsed=${elapsed}s remaining=$((wait_seconds - elapsed))s"
  done
}

log "=== PF_login v0.10.86 GENERATE PROOFRUNNER / recovery engine proof bundle ==="
log "Run timestamp: $RUN_TS"
log "Script dir: $SCRIPT_DIR"
log "Repo zip: $REPO_ZIP"
log "Run dir: $RUN_DIR"
log "Main log: $MAIN_LOG"
log "Visual evidence dir: $VISUAL_EVIDENCE_DIR"
log "Seconds runtime defaults: PF_V2_CRON_RUNTIME_WAIT_SECONDS=${PF_V2_CRON_RUNTIME_WAIT_SECONDS:-90}, PF_V2_CRON_PROOF_SECONDS=${PF_V2_CRON_PROOF_SECONDS:-45}, PF_V2_CRON_PROOF_INTERVAL_SECONDS=${PF_V2_CRON_PROOF_INTERVAL_SECONDS:-5}, PF_V2_PRODUCTION_CRON_RUNTIME_WAIT_SECONDS=${PF_V2_PRODUCTION_CRON_RUNTIME_WAIT_SECONDS:-75}"

append_summary "PF_login prooflauncher run $RUN_TS"
append_summary "script=prooflauncher_raspberry.sh"
append_summary "repo_zip=$REPO_ZIP"
append_summary "run_dir=$RUN_DIR"
append_summary "visual_evidence_dir=$VISUAL_EVIDENCE_DIR"
append_summary "required_only=1"
append_summary "runs_full_npm_test=0"

write_visual_instructions
copy_seeded_visual_evidence
log "Opening visual evidence folder. Add screen photo/video evidence there when available."
open_folder "$VISUAL_EVIDENCE_DIR"

if [ ! -f "$REPO_ZIP" ]; then
  log "ERROR: repo ZIP not found: $REPO_ZIP"
  append_summary "repo_zip_missing=1"
else
  log "Extracting repo ZIP."
  unzip -o "$REPO_ZIP" -d "$WORKSPACE" 2>&1 | tee "$CMD_LOG_DIR/00_unzip.log"

  REPO_ROOT="$(find "$WORKSPACE" -maxdepth 5 -type f -name package.json -printf '%h\n' | head -n 1 || true)"
  if [ -z "${REPO_ROOT:-}" ]; then
    log "ERROR: package.json not found after extracting repo."
    append_summary "repo_root_missing=1"
  else
    cd "$REPO_ROOT" || true
    log "Repo root: $REPO_ROOT"

    export PF_V2_VISUAL_EVIDENCE_DIR="$VISUAL_EVIDENCE_DIR"
    export PF_V2_CRON_RUNTIME_WAIT_SECONDS="${PF_V2_CRON_RUNTIME_WAIT_SECONDS:-90}"
    export PF_V2_CRON_PROOF_SECONDS="${PF_V2_CRON_PROOF_SECONDS:-45}"
    export PF_V2_CRON_PROOF_INTERVAL_SECONDS="${PF_V2_CRON_PROOF_INTERVAL_SECONDS:-5}"
    export PF_V2_PRODUCTION_CRON_RUNTIME_WAIT_SECONDS="${PF_V2_PRODUCTION_CRON_RUNTIME_WAIT_SECONDS:-75}"

    {
      echo "PWD=$(pwd)"
      echo "VERSION=$(cat VERSION 2>/dev/null || true)"
      echo "Node=$(node --version 2>/dev/null || true)"
      echo "npm=$(npm --version 2>/dev/null || true)"
      echo "npm registry=$(npm config get registry 2>/dev/null || true)"
      echo "Git HEAD=$(git rev-parse --short HEAD 2>/dev/null || true)"
      echo "crontab=$(command -v crontab 2>/dev/null || true)"
      echo "PF_V2_VISUAL_EVIDENCE_DIR=$PF_V2_VISUAL_EVIDENCE_DIR"
      echo "PATH=$PATH"
      echo "Git status:"
      git status --short 2>/dev/null || true
    } | tee "$CMD_LOG_DIR/environment.log"

    log "Forcing public npm registry for target runs."
    printf '%s\n' 'registry=https://registry.npmjs.org/' > .npmrc

    run_shell_cmd "01_npm_install_verbose" "npm install --verbose --registry=https://registry.npmjs.org/"

    # REQUIRED PROOFS ONLY. This intentionally does NOT run npm test or every proof.
    run_shell_cmd "02_proof_v2_real_machine_readiness" "npm run proof:v2-real-machine-readiness"
    run_shell_cmd "03_proof_v2_recovery_engine_contract" "npm run proof:v2-recovery-engine-contract"
    run_shell_cmd "04_proof_v2_recovery_engine" "npm run proof:v2-recovery-engine"
    run_shell_cmd "05_proof_v2_recovery_emulate_power_off" "npm run proof:v2-recovery-emulate-power-off"
    run_shell_cmd "06_proof_v2_recovery_restart_check" "npm run proof:v2-recovery-restart-check"
    run_shell_cmd "07_proof_v2_install_real_crontab" "npm run proof:v2-install-real-crontab"
    run_shell_cmd "08_proof_v2_real_cron_runtime" "npm run proof:v2-real-cron-runtime"
    run_shell_cmd "09_proof_v2_install_production_crontab" "PF_V2_CRON_MODE=production npm run proof:v2-install-production-crontab"
    run_shell_cmd "10_proof_v2_production_cron_runtime" "npm run proof:v2-production-cron-runtime"
    run_shell_cmd "11_proof_v2_real_cron_evidence" "npm run proof:v2-real-cron-evidence"
    run_shell_cmd "12_proof_v2_real_playback_display" "npm run proof:v2-real-playback-display"
    run_shell_cmd "13_proof_v2_autonomous_contract" "npm run proof:v2-autonomous-contract"
    wait_for_visual_evidence_if_requested
    run_shell_cmd "14_proof_v2_visual_physical_evidence" "npm run proof:v2-visual-physical-evidence"
    run_shell_cmd "15_proof_v2_final_autonomous_bundle" "npm run proof:v2-final-autonomous-bundle"

    log "Optional cleanup is available but not run by default: npm run proof:v2-real-cron-cleanup and npm run proof:v2-production-cron-cleanup"
    capture_artifacts "$REPO_ROOT"
  fi
fi

zip_run_folder
log "Opening folder containing prooflauncher ZIP: $RUN_PARENT"
open_folder "$RUN_PARENT"

printf '\n============================================================\n'
printf 'PROOFRUNNER FINISHED.\n'
printf 'UPLOAD THIS ZIP BACK TO CHATGPT:\n%s\n' "$RESULT_ZIP"
printf '\nSHA256 FILE:\n%s.sha256\n' "$RESULT_ZIP"
printf '============================================================\n\n'

if [ -t 0 ]; then
  read -r -p "Done. Press Enter to return to shell..." _unused || true
fi
