# Windows live native recovery proof runner for PF_login / 1234_PF.
# Creates a proof-only env file and lets the Node proof runner own API stop/restart orchestration.
# Runs proof:live-windows-native-recovery against the actual API port used by this runner.
# Stops only the API process started by this script and never changes normal launcher defaults.
# Packs runtime logs/proofs/artifacts into a Downloads evidence ZIP for easy upload.

[CmdletBinding()]
param(
    [int] $ApiPort = 4301,
    [switch] $WorkerAutostart,
    [switch] $SkipEvidenceCleanup,
    [switch] $KeepApiRunning,
    [string] $RepoRoot = ""
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

if ([string]::IsNullOrWhiteSpace($RepoRoot)) {
    $scriptRoot = if ($PSScriptRoot) { $PSScriptRoot } else { Split-Path -Parent $PSCommandPath }
    $RepoRoot = (Resolve-Path (Join-Path $scriptRoot "..")).Path
} else {
    $RepoRoot = (Resolve-Path $RepoRoot).Path
}

$ApiBaseUrl = "http://127.0.0.1:$ApiPort"
$MpvPath = Join-Path $RepoRoot "tools\mpv\windows\mpv.exe"
$GeneratedEnvPath = Join-Path $RepoRoot "runtime_data\live_windows_native_recovery_proof.env"
$ApiStdoutPath = Join-Path $RepoRoot "logs\live_windows_native_recovery_api.stdout.log"
$ApiStderrPath = Join-Path $RepoRoot "logs\live_windows_native_recovery_api.stderr.log"

<#
Writes a timestamped runner message for clear operator-visible proof progress.
#>
function Write-ProofStep {
    param(
        [Parameter(Mandatory = $true)]
        [string] $Message,
        [string] $Color = "Cyan"
    )
    Write-Host "[$((Get-Date).ToString('HH:mm:ss'))] $Message" -ForegroundColor $Color
}

<#
Runs one command in the repository root and throws when it exits with a non-zero code.
#>
function Invoke-RepoCommand {
    param(
        [Parameter(Mandatory = $true)]
        [string] $FilePath,
        [Parameter(Mandatory = $true)]
        [string[]] $Arguments,
        [Parameter(Mandatory = $true)]
        [string] $StepName
    )

    Write-ProofStep $StepName
    Push-Location $RepoRoot
    try {
        & $FilePath @Arguments
        if ($LASTEXITCODE -ne 0) {
            throw "$StepName failed with exit code $LASTEXITCODE."
        }
    }
    finally {
        Pop-Location
    }
}

<#
Removes generated evidence from prior runs while preserving tracked placeholders/docs.
#>
function Clear-GeneratedEvidence {
    if ($SkipEvidenceCleanup) {
        Write-ProofStep "Skipping evidence cleanup by request." "Yellow"
        return
    }

    Write-ProofStep "Cleaning generated logs/proofs/artifacts for a fresh native playback proof." "Yellow"
    $pathsToClean = @(
        "runtime_data\proofs",
        "runtime_data\artifacts",
        "runtime_data\reports",
        "logs"
    )

    foreach ($relativePath in $pathsToClean) {
        $path = Join-Path $RepoRoot $relativePath
        if (-not (Test-Path $path)) {
            New-Item -ItemType Directory -Force -Path $path | Out-Null
            continue
        }

        Get-ChildItem $path -Force -ErrorAction SilentlyContinue |
            Where-Object { $_.Name -notin @(".gitkeep", "README.md") } |
            Remove-Item -Recurse -Force -ErrorAction SilentlyContinue
    }
}

<#
Ensures repo-local mpv exists by delegating to the installer script.
#>
function Ensure-RepoLocalMpv {
    $installerScript = Join-Path $RepoRoot "scripts\install_mpv_windows.ps1"
    if (-not (Test-Path $installerScript)) {
        throw "mpv installer script not found: $installerScript"
    }

    Write-ProofStep "Verifying/installing repo-local mpv for proof mode."
    Push-Location $RepoRoot
    try {
        & powershell -NoProfile -ExecutionPolicy Bypass -File $installerScript -RepoRoot $RepoRoot
        if ($LASTEXITCODE -ne 0) {
            throw "mpv installer failed or was blocked with exit code $LASTEXITCODE."
        }
    }
    finally {
        Pop-Location
    }

    if (-not (Test-Path $MpvPath)) {
        throw "mpv.exe was not found after installer completed: $MpvPath"
    }
}

<#
Creates a proof-only env file by copying .env and appending native playback overrides last.
#>
function New-ProofEnvironmentFile {
    $repoEnvPath = Join-Path $RepoRoot ".env"
    if (-not (Test-Path $repoEnvPath)) {
        $parentEnvPath = Join-Path (Split-Path $RepoRoot -Parent) ".env"
        if (Test-Path $parentEnvPath) {
            Copy-Item -Path $parentEnvPath -Destination $repoEnvPath -Force
        } else {
            throw ".env not found in repo root or parent folder."
        }
    }

    New-Item -ItemType Directory -Force -Path (Split-Path $GeneratedEnvPath -Parent) | Out-Null
    $baseEnv = Get-Content -Path $repoEnvPath -Raw
    $overrides = @(
        "",
        "# Proof-only overrides generated by start_live_windows_native_recovery_proof.cmd.",
        "NATIVE_PLAYBACK_ENABLED=true",
        "NATIVE_PLAYBACK_AUTO_START_ON_WORKER=true",
        "NATIVE_PLAYBACK_FULLSCREEN=true",
        "NATIVE_PLAYBACK_PLAYER=mpv",
        "NATIVE_PLAYBACK_PLAYER_PATH=$MpvPath"
    ) -join "`r`n"

    Set-Content -Path $GeneratedEnvPath -Encoding UTF8 -Value ($baseEnv.TrimEnd() + "`r`n" + $overrides + "`r`n")
    Write-ProofStep "Generated proof-only env file: $GeneratedEnvPath"
}

<#
Starts an owned API process with native playback enabled through INIT_ENV_FILE.
#>
function Start-ProofApiProcess {
    Write-ProofStep "Starting proof-only API on $ApiBaseUrl with native playback enabled."
    New-Item -ItemType Directory -Force -Path (Join-Path $RepoRoot "logs") | Out-Null

    $previousInitEnv = $env:INIT_ENV_FILE
    $previousPort = $env:PORT
    try {
        $env:INIT_ENV_FILE = $GeneratedEnvPath
        $env:PORT = [string]$ApiPort
        $process = Start-Process -FilePath "node" `
            -ArgumentList @("--import", "tsx", "server/index.ts") `
            -WorkingDirectory $RepoRoot `
            -RedirectStandardOutput $ApiStdoutPath `
            -RedirectStandardError $ApiStderrPath `
            -PassThru
        return $process
    }
    finally {
        if ($null -eq $previousInitEnv) { Remove-Item Env:\INIT_ENV_FILE -ErrorAction SilentlyContinue } else { $env:INIT_ENV_FILE = $previousInitEnv }
        if ($null -eq $previousPort) { Remove-Item Env:\PORT -ErrorAction SilentlyContinue } else { $env:PORT = $previousPort }
    }
}

<#
Waits until the proof API responds and confirms native playback is enabled.
#>
function Wait-ForNativeProofApi {
    param(
        [Parameter(Mandatory = $true)]
        [System.Diagnostics.Process] $Process,
        [int] $TimeoutSeconds = 45
    )

    $deadline = (Get-Date).AddSeconds($TimeoutSeconds)
    do {
        if ($Process.HasExited) {
            throw "Proof API exited early with code $($Process.ExitCode). See $ApiStdoutPath and $ApiStderrPath."
        }

        try {
            $status = Invoke-RestMethod "$ApiBaseUrl/api/native-playback/status" -TimeoutSec 3
            if ($status.config.enabled -eq $true) {
                Write-ProofStep "Proof API reports native playback enabled."
                return $status
            }
            throw "Proof API responded, but native playback is still disabled."
        }
        catch {
            Start-Sleep -Milliseconds 750
        }
    } while ((Get-Date) -lt $deadline)

    throw "Timed out waiting for proof API at $ApiBaseUrl with native playback enabled."
}

<#
Runs the live native recovery proof against the API started by this script.
#>
function Invoke-LiveNativeProof {
    param(
        [bool] $RunWorkerAutostart
    )

    $previous = @{
        PF_API_BASE_URL = $env:PF_API_BASE_URL
        PF_LIVE_WINDOWS_NATIVE_PLAYBACK_PROOF = $env:PF_LIVE_WINDOWS_NATIVE_PLAYBACK_PROOF
        PF_LIVE_WINDOWS_NATIVE_PLAYBACK_RUNTIME_MODE = $env:PF_LIVE_WINDOWS_NATIVE_PLAYBACK_RUNTIME_MODE
        PF_LIVE_WINDOWS_NATIVE_PLAYBACK_WORKER_AUTOSTART = $env:PF_LIVE_WINDOWS_NATIVE_PLAYBACK_WORKER_AUTOSTART
        PF_LIVE_WINDOWS_NATIVE_RECOVERY_PROOF = $env:PF_LIVE_WINDOWS_NATIVE_RECOVERY_PROOF
        PF_LIVE_WINDOWS_NATIVE_RECOVERY_ORCHESTRATE = $env:PF_LIVE_WINDOWS_NATIVE_RECOVERY_ORCHESTRATE
        PORT = $env:PORT
        NATIVE_PLAYBACK_ENABLED = $env:NATIVE_PLAYBACK_ENABLED
        NATIVE_PLAYBACK_AUTO_START_ON_WORKER = $env:NATIVE_PLAYBACK_AUTO_START_ON_WORKER
        NATIVE_PLAYBACK_FULLSCREEN = $env:NATIVE_PLAYBACK_FULLSCREEN
        NATIVE_PLAYBACK_PLAYER = $env:NATIVE_PLAYBACK_PLAYER
        NATIVE_PLAYBACK_PLAYER_PATH = $env:NATIVE_PLAYBACK_PLAYER_PATH
        INIT_ENV_FILE = $env:INIT_ENV_FILE
    }

    try {
        $env:PF_API_BASE_URL = $ApiBaseUrl
        $env:PF_LIVE_WINDOWS_NATIVE_PLAYBACK_PROOF = "1"
        $env:PF_LIVE_WINDOWS_NATIVE_PLAYBACK_RUNTIME_MODE = "real"
        $env:PF_LIVE_WINDOWS_NATIVE_RECOVERY_PROOF = "1"
        $env:PF_LIVE_WINDOWS_NATIVE_RECOVERY_ORCHESTRATE = "1"
        $env:PORT = [string]$ApiPort
        $env:NATIVE_PLAYBACK_ENABLED = "true"
        $env:NATIVE_PLAYBACK_AUTO_START_ON_WORKER = "true"
        $env:NATIVE_PLAYBACK_FULLSCREEN = "true"
        $env:NATIVE_PLAYBACK_PLAYER = "mpv"
        $env:NATIVE_PLAYBACK_PLAYER_PATH = $MpvPath
        $env:INIT_ENV_FILE = $GeneratedEnvPath
        if ($RunWorkerAutostart) {
            $env:PF_LIVE_WINDOWS_NATIVE_PLAYBACK_WORKER_AUTOSTART = "1"
        } else {
            Remove-Item Env:\PF_LIVE_WINDOWS_NATIVE_PLAYBACK_WORKER_AUTOSTART -ErrorAction SilentlyContinue
        }

        Invoke-RepoCommand -FilePath "npm" -Arguments @("run", "proof:live-windows-native-recovery") -StepName "Run live Windows native recovery proof"
    }
    finally {
        foreach ($key in $previous.Keys) {
            if ($null -eq $previous[$key]) {
                Remove-Item "Env:\$key" -ErrorAction SilentlyContinue
            } else {
                Set-Item "Env:\$key" $previous[$key]
            }
        }
    }
}

<#
Stops only the API process started by this proof runner.
#>
function Stop-ProofApiProcess {
    param(
        [System.Diagnostics.Process] $Process
    )

    if ($KeepApiRunning) {
        Write-ProofStep "Keeping proof API process running by request. PID=$($Process.Id)" "Yellow"
        return
    }

    if ($null -ne $Process -and -not $Process.HasExited) {
        Write-ProofStep "Stopping owned proof API process PID=$($Process.Id)."
        Stop-Process -Id $Process.Id -Force -ErrorAction SilentlyContinue
    }
}

<#
Packs logs, reports, artifacts, and proof JSON into a Downloads ZIP and opens Explorer.
#>
function Export-EvidenceZip {
    $stamp = Get-Date -Format "yyyy-MM-dd_HH-mm-ss"
    $downloads = Join-Path $env:USERPROFILE "Downloads"
    $outDir = Join-Path $downloads "PF_login_native_recovery_evidence_$stamp"
    $zipPath = "$outDir.zip"
    New-Item -ItemType Directory -Force -Path $outDir | Out-Null

    foreach ($relativeSource in @("runtime_data\proofs", "runtime_data\artifacts", "runtime_data\reports", "logs")) {
        $source = Join-Path $RepoRoot $relativeSource
        if (Test-Path $source) {
            $destination = Join-Path $outDir (Split-Path $relativeSource -Leaf)
            Copy-Item $source $destination -Recurse -Force
        }
    }

    $latestProof = Get-ChildItem (Join-Path $RepoRoot "runtime_data\proofs\live_windows_native_recovery_*.json") -ErrorAction SilentlyContinue |
        Sort-Object LastWriteTime -Descending |
        Select-Object -First 1

    $summaryPath = Join-Path $outDir "summary.txt"
    @"
PF_login live Windows native recovery proof bundle
Generated: $(Get-Date -Format o)
Repo: $RepoRoot
Version: $(Get-Content (Join-Path $RepoRoot 'VERSION') -Raw)
Git:
$(git -C $RepoRoot log --oneline -5 | Out-String)
Git status:
$(git -C $RepoRoot status --short | Out-String)
API base: $ApiBaseUrl
mpv exists: $(Test-Path $MpvPath)
latest proof: $($latestProof.FullName)
API stdout: $ApiStdoutPath
API stderr: $ApiStderrPath
"@ | Set-Content -Path $summaryPath -Encoding UTF8

    if (Test-Path $zipPath) { Remove-Item $zipPath -Force }
    Compress-Archive -Path "$outDir\*" -DestinationPath $zipPath -Force
    Write-ProofStep "Evidence ZIP created: $zipPath" "Green"
    explorer.exe /select,"$zipPath"
}

$apiProcess = $null
try {
    Write-ProofStep "PF_login live Windows native recovery proof launcher."
    Push-Location $RepoRoot
    try {
        Clear-GeneratedEvidence
        Invoke-RepoCommand -FilePath "npm" -Arguments @("install", "--verbose") -StepName "Install dependencies"
        Ensure-RepoLocalMpv
        New-ProofEnvironmentFile
        $proofFailure = $null
        try {
            Invoke-LiveNativeProof -RunWorkerAutostart:$($WorkerAutostart.IsPresent)
        }
        catch {
            $proofFailure = $_
            Write-ProofStep "Live native recovery proof failed; exporting evidence before exiting." "Yellow"
        }
        Export-EvidenceZip
        if ($null -ne $proofFailure) {
            throw $proofFailure
        }
    }
    finally {
        Pop-Location
    }
}
finally {
    if ($null -ne $apiProcess) {
        Stop-ProofApiProcess -Process $apiProcess
    }
}
