#!/usr/bin/env node
// Maintains repository version metadata for commits and release checks.
// Validates VERSION, package metadata, and the newest changelog entry.
// Prepares patch/minor/major bumps from conventional commit messages.
// Keeps legacy changelog history readable while enforcing structured entries.
import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { execFileSync } from 'node:child_process';
const ROOT = process.cwd();
const REQUIRED_SECTIONS = ['Added', 'Changed', 'Fixed', 'Removed'];
const ENFORCEMENT_VERSION = '0.3.3';
const META_FILES = ['VERSION', 'CHANGELOG.md', 'package.json', 'package-lock.json'];
function readText(p){return fs.readFileSync(path.join(ROOT,p),'utf8');}
function readJson(p){return JSON.parse(readText(p));}
function git(args){return execFileSync('git',args,{cwd:ROOT,encoding:'utf8',stdio:['ignore','pipe','pipe']}).trim();}
function hasGit(){try{git(['rev-parse','--is-inside-work-tree']);return true;}catch{return false;}}
function stagedFiles(){if(!hasGit()) return []; return git(['diff','--cached','--name-only']).split(/\r?\n/).map(x=>x.trim()).filter(Boolean);}
function parseSemver(v){const m=/^(\d+)\.(\d+)\.(\d+)$/.exec(String(v).trim()); if(!m) throw new Error(`Invalid semantic version: ${v}`); return {raw:`${m[1]}.${m[2]}.${m[3]}`,major:+m[1],minor:+m[2],patch:+m[3]};}
function cmp(a,b){return a.major-b.major || a.minor-b.minor || a.patch-b.patch;}
function bumpKind(prev,next){if(next.major>prev.major) return 'major'; if(next.minor>prev.minor) return 'minor'; if(next.patch>prev.patch) return 'patch'; return 'none';}
function normalizeCommitMessage(message){ const raw=String(message); const match=raw.match(/^([^\r\n]*)([\s\S]*)$/); const header=(match?.[1] ?? '').trim(); const rest=match?.[2] ?? ''; if(!header) throw new Error('Commit message must not be empty.'); if(/^(feat|fix|docs|refactor|test|chore)(\([^)]+\))?(!)?:\s.+$/.test(header)) return {message:raw, normalized:false}; if(/^[a-z]+(\([^)]+\))?(!)?:/.test(header)) throw new Error('Commit message must follow Conventional Commits: feat|fix|docs|refactor|test|chore with optional scope and ! marker.'); return {message:`chore: ${header}${rest}`, normalized:true}; }
function parseCommitMessage(message){const text=message.trim(); const [header]=text.split(/\r?\n/); const m=/^(feat|fix|docs|refactor|test|chore)(\([^)]+\))?(!)?:\s.+$/.exec(header); if(!m) throw new Error('Commit message must follow Conventional Commits: feat|fix|docs|refactor|test|chore with optional scope and ! marker.'); const breaking=Boolean(m[3]) || /(^|\n)BREAKING CHANGE:\s+/m.test(text); return {type:m[1], requiredBump: breaking ? 'major' : m[1]==='feat' ? 'minor' : 'patch'}; }
function prependChangelogEntry(changelog,entry){ const firstEntry=changelog.match(/^##\s+\d{4}-\d{2}-\d{2} \d{2}:\d{2} (?:EET|EEST) — v\d+\.\d+\.\d+\s*$/m); if(firstEntry?.index!=null) return `${changelog.slice(0,firstEntry.index)}${entry}${changelog.slice(firstEntry.index)}`; const heading=changelog.match(/^# CHANGELOG\s*$/m); if(!heading?.index && heading?.index!==0) throw new Error('CHANGELOG.md must start with "# CHANGELOG".'); const insertAt=heading.index + heading[0].length; return `${changelog.slice(0,insertAt)}\n\n${entry}${changelog.slice(insertAt).replace(/^\n*/,'')}`; }
function lastSundayUtcDay(year,monthIndex){ const end=new Date(Date.UTC(year,monthIndex+1,0)); return end.getUTCDate()-end.getUTCDay(); }
function tallinnSuffix(date){ const y=date.getUTCFullYear(); const start=Date.UTC(y,2,lastSundayUtcDay(y,2),1,0,0); const end=Date.UTC(y,9,lastSundayUtcDay(y,9),1,0,0); const t=date.getTime(); return t>=start && t<end ? 'EEST':'EET'; }
function formatTallinn(date=new Date()){ const fmt=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Tallinn',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}); const parts=Object.fromEntries(fmt.formatToParts(date).map(p=>[p.type,p.value])); return `${parts.year}-${parts.month}-${parts.day} ${parts.hour}:${parts.minute} ${tallinnSuffix(date)}`; }
// Parses structured changelog entries and stops each entry at the next H2 heading,
// allowing newer structured entries to coexist with preserved legacy headings.
function parseChangelogEntries(text){
 const lines=text.split(/\r?\n/); const entries=[]; let cur=null;
 for(const line of lines){
  const m=/^##\s+(\d{4}-\d{2}-\d{2} \d{2}:\d{2} (?:EET|EEST))\s+—\s+v(\d+\.\d+\.\d+)\s*$/.exec(line);
  if(m){ if(cur) entries.push(cur); cur={timestamp:m[1],version:m[2],bodyLines:[]}; continue; }
  if(cur && /^##\s+/.test(line)){ entries.push(cur); cur=null; }
  if(cur) cur.bodyLines.push(line);
 }
 if(cur) entries.push(cur); return entries;
}
function validateStructuredEntry(entry){ const body=entry.bodyLines.join('\n'); const sections=[...body.matchAll(/^###\s+(Added|Changed|Fixed|Removed)\s*$/gm)].map(m=>m[1]); if(sections.length!==4 || new Set(sections).size!==4) throw new Error(`Changelog entry v${entry.version} must include exactly these sections: ${REQUIRED_SECTIONS.join(', ')}`); for(const section of REQUIRED_SECTIONS){ const re=new RegExp(`###\\s+${section}\\s*\\n([\\s\\S]*?)(?=\\n###\\s+|$)`); const m=body.match(re); if(!m) throw new Error(`Changelog entry v${entry.version} is missing section ${section}.`); const items=m[1].split(/\r?\n/).map(x=>x.trim()).filter(Boolean); if(!items.length) throw new Error(`Changelog entry v${entry.version} section ${section} must contain at least one bullet.`); if(items.some(x=>!x.startsWith('- '))) throw new Error(`Changelog entry v${entry.version} section ${section} must use bullet lines.`); } }
function validateRepo({requireGit=false}={}){ const version=parseSemver(readText('VERSION')); const pkg=parseSemver(readJson('package.json').version); const lockJson=readJson('package-lock.json'); const lock=parseSemver(lockJson.version); const lockRoot=parseSemver(lockJson.packages[''].version); if(cmp(version,pkg)!==0) throw new Error(`VERSION (${version.raw}) and package.json (${pkg.raw}) must match.`); if(cmp(version,lock)!==0) throw new Error(`VERSION (${version.raw}) and package-lock.json (${lock.raw}) must match.`); if(cmp(version,lockRoot)!==0) throw new Error(`VERSION (${version.raw}) and package-lock.json packages[""].version (${lockRoot.raw}) must match.`); const entries=parseChangelogEntries(readText('CHANGELOG.md')); if(!entries.length) throw new Error('CHANGELOG.md must contain at least one version entry.'); if(entries[0].version!==version.raw) throw new Error(`Latest CHANGELOG entry version (${entries[0].version}) must match VERSION (${version.raw}).`); if(cmp(version,parseSemver(ENFORCEMENT_VERSION))>=0) validateStructuredEntry(entries[0]); if(requireGit){ if(!hasGit()) throw new Error('Git repository not available for staged-change validation.'); const staged=stagedFiles(); const missing=missingMetaForCommit(staged); if(missing.length) throw new Error(`Staged change set must include ${missing[0]} whenever other repository files are being committed.`); } return version.raw; }
function validateCommitMessage(message){ const parsed=parseCommitMessage(message); if(hasGit()){ try{ const head=parseSemver(git(['show','HEAD:VERSION'])); const current=parseSemver(readText('VERSION')); const actual=bumpKind(head,current); const rank={none:0,patch:1,minor:2,major:3}; if(rank[actual] < rank[parsed.requiredBump]) throw new Error(`Commit message requires a ${parsed.requiredBump} bump, but VERSION only changed from ${head.raw} to ${current.raw} (${actual}).`); }catch(err){ if(!/fatal: invalid object name 'HEAD'/.test(String(err.stderr||'')) && !/exists on disk, but not in 'HEAD'/.test(String(err.stderr||''))) throw err; } }
 return parsed; }
function stageMetaFiles(files=META_FILES){ if(!files.length) return; git(['add','--',...files]); }
function stagedCommitNeedsMeta(staged){ if(!staged.length) return false; const meta=new Set(META_FILES); return staged.some(f=>!meta.has(f)); }
function missingMetaForCommit(staged){ return stagedCommitNeedsMeta(staged) ? META_FILES.filter(f=>!staged.includes(f)) : []; }
function prepareForCommit(message){ const staged=stagedFiles(); if(!stagedCommitNeedsMeta(staged)) return; try{ validateRepo(); validateCommitMessage(message); stageMetaFiles(); console.log('Staged existing version metadata for this commit.'); return; }catch{ prepare(message); stageMetaFiles(); console.log('Auto-prepared and staged version metadata for this commit.'); } }
function prepare(message){ const normalized=normalizeCommitMessage(message); const parsed=parseCommitMessage(normalized.message); const cur=parseSemver(readText('VERSION')); const nxt={...cur}; if(parsed.requiredBump==='major'){nxt.major++; nxt.minor=0; nxt.patch=0;} else if(parsed.requiredBump==='minor'){nxt.minor++; nxt.patch=0;} else {nxt.patch++;} const next=`${nxt.major}.${nxt.minor}.${nxt.patch}`; fs.writeFileSync(path.join(ROOT,'VERSION'),`${next}\n`); const pkg=readJson('package.json'); pkg.version=next; fs.writeFileSync(path.join(ROOT,'package.json'),JSON.stringify(pkg,null,2)+'\n'); const lock=readJson('package-lock.json'); lock.version=next; if(lock.packages?.['']) lock.packages[''].version=next; fs.writeFileSync(path.join(ROOT,'package-lock.json'),JSON.stringify(lock,null,2)+'\n'); let changelog=readText('CHANGELOG.md'); const note='> Note: changelog entries before v0.3.3 are preserved as legacy history and are not backfilled. Structured forward-only enforcement begins at v0.3.3.\n\n'; if(!changelog.includes('Structured forward-only enforcement begins at v0.3.3') && !changelog.includes('structured forward-only enforcement begins at v0.3.3')) changelog=changelog.replace('# CHANGELOG\n\n',`# CHANGELOG\n\n${note}`); const entries=parseChangelogEntries(changelog); if(entries[0]?.version!==next){ const entry=`## ${formatTallinn()} — v${next}\n\n### Added\n- None\n\n### Changed\n- None\n\n### Fixed\n- None\n\n### Removed\n- None\n\n`; changelog=prependChangelogEntry(changelog,entry); fs.writeFileSync(path.join(ROOT,'CHANGELOG.md'),changelog); } console.log(`Prepared version ${next} (${parsed.requiredBump} bump).`); }
const [mode,...args]=process.argv.slice(2);
try{
 if(mode==='repo'){ console.log(`Repo version state OK for ${validateRepo({requireGit:args.includes('--staged')})}.`); }
 else if(mode==='commit-msg'){ const fi=args.indexOf('--commit-msg-file'); const mi=args.indexOf('--message'); let msg=''; let msgFile=''; if(fi>=0 && args[fi+1]){ msgFile=path.resolve(ROOT,args[fi+1]); msg=fs.readFileSync(msgFile,'utf8'); } else if(mi>=0 && args[mi+1]) msg=args[mi+1]; else throw new Error('commit-msg mode requires --commit-msg-file <path> or --message <text>.'); const normalized=normalizeCommitMessage(msg); msg=normalized.message; if(normalized.normalized){ if(msgFile) fs.writeFileSync(msgFile,msg); console.log(`Auto-normalized commit message to "${msg.split(/\r?\n/,1)[0]}".`); } prepareForCommit(msg); validateRepo({requireGit:true}); const parsed=validateCommitMessage(msg); console.log(`Commit message OK (${parsed.type}, required bump: ${parsed.requiredBump}).`); }
 else if(mode==='prepare'){ const mi=args.indexOf('--message'); if(mi<0||!args[mi+1]) throw new Error('prepare mode requires --message <text>.'); prepare(args[mi+1]); }
 else throw new Error('Unknown mode');
}catch(err){ console.error(`ERROR: ${err.message}`); process.exit(1); }
